### ISSUE TITLE
Screen Freeze Due to Shader Error

### ISSUE THREAD

**Issue by threehymns** [paradust7/minetest-wasm#27]
```Console
2023-09-20 13:59:15: ERROR[Main]: In thread 1862b8:
app.js:499 2023-09-20 13:59:15: ERROR[Main]: /home/mtuser/minetest-wasm/sources/minetest/src/client/shader.cpp:125: virtual void MainShaderConstantSetter::onSetConstants(video::IMaterialRendererServices *): An engine assumption 'normal.makeInverse()' failed.
app.js:499 Aborted()
app.js:499 Exception thrown, see JavaScript console
minetest.js:1 Uncaught RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (minetest.js:1:9937)
    at _abort (minetest.js:1:47874)
    at minetest.wasm:0x12e1b
    at minetest.wasm:0xa8eb0a
    at minetest.wasm:0xa8b3c6
    at minetest.wasm:0x5ff59b
    at minetest.wasm:0x139133
    at minetest.wasm:0x328c67
    at minetest.wasm:0x5f5f8c
    at minetest.wasm:0x5fcf10
app.js:499 PointerLockChange: isActive=0
10app.js:499 [WARNING] MainLoop attempted reentry

```

**Comment by paradust7** [comment]
I need a lot more information. Is this crash reproducible? How can I reproduce it?

**Comment by threehymns** [comment]
Sorry, I don't have a whole lot more info except that I was playing on a server at the time with default settings.

I posted all the information the devtools console gave me.

**Comment by paradust7** [comment]
Can't determine what happened here, and this code is no longer present in upstream minetest, so closing. Please re-open if you find a way to reproduce it.
